CREATE TABLE accounts (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    account_number VARCHAR(20) NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL,
    description TEXT NULL,
    account_type_id INT UNSIGNED NOT NULL,
    account_subtype_id INT UNSIGNED NULL,
    parent_id INT UNSIGNED NULL,
    currency_code CHAR(3) NOT NULL DEFAULT 'USD',
    is_header TINYINT(1) NOT NULL DEFAULT 0,
    is_active TINYINT(1) NOT NULL DEFAULT 1,
    is_system TINYINT(1) NOT NULL DEFAULT 0,
    is_bank_account TINYINT(1) NOT NULL DEFAULT 0,
    opening_balance DECIMAL(15,2) NOT NULL DEFAULT 0.00,
    created_by INT UNSIGNED NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_accounts_type (account_type_id),
    INDEX idx_accounts_parent (parent_id),
    INDEX idx_accounts_active (is_active),
    FOREIGN KEY (account_type_id) REFERENCES account_types(id),
    FOREIGN KEY (account_subtype_id) REFERENCES account_subtypes(id),
    FOREIGN KEY (parent_id) REFERENCES accounts(id),
    FOREIGN KEY (created_by) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
