CREATE TABLE journal_entries (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    entry_number VARCHAR(20) NOT NULL UNIQUE,
    entry_date DATE NOT NULL,
    description VARCHAR(500) NOT NULL,
    reference VARCHAR(100) NULL,
    status ENUM('draft','posted','voided') NOT NULL DEFAULT 'draft',
    source_type VARCHAR(50) NULL,
    source_id INT UNSIGNED NULL,
    fiscal_year_id INT UNSIGNED NULL,
    fiscal_period_id INT UNSIGNED NULL,
    posted_at DATETIME NULL,
    posted_by INT UNSIGNED NULL,
    voided_at DATETIME NULL,
    voided_by INT UNSIGNED NULL,
    void_reason VARCHAR(500) NULL,
    reversing_entry_id INT UNSIGNED NULL,
    notes TEXT NULL,
    created_by INT UNSIGNED NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_je_date (entry_date),
    INDEX idx_je_status (status),
    INDEX idx_je_source (source_type, source_id),
    INDEX idx_je_period (fiscal_period_id),
    FOREIGN KEY (fiscal_year_id) REFERENCES fiscal_years(id),
    FOREIGN KEY (fiscal_period_id) REFERENCES fiscal_periods(id),
    FOREIGN KEY (posted_by) REFERENCES users(id),
    FOREIGN KEY (voided_by) REFERENCES users(id),
    FOREIGN KEY (reversing_entry_id) REFERENCES journal_entries(id),
    FOREIGN KEY (created_by) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
