CREATE TABLE invoices (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    document_type ENUM('invoice','bill','credit_note') NOT NULL,
    document_number VARCHAR(30) NOT NULL UNIQUE,
    contact_id INT UNSIGNED NOT NULL,
    issue_date DATE NOT NULL,
    due_date DATE NOT NULL,
    subtotal DECIMAL(15,2) NOT NULL DEFAULT 0.00,
    tax_amount DECIMAL(15,2) NOT NULL DEFAULT 0.00,
    total DECIMAL(15,2) NOT NULL DEFAULT 0.00,
    amount_paid DECIMAL(15,2) NOT NULL DEFAULT 0.00,
    balance_due DECIMAL(15,2) NOT NULL DEFAULT 0.00,
    currency_code CHAR(3) NOT NULL DEFAULT 'USD',
    status ENUM('draft','sent','partial','paid','overdue','voided') NOT NULL DEFAULT 'draft',
    terms TEXT NULL,
    notes TEXT NULL,
    journal_entry_id INT UNSIGNED NULL,
    ar_ap_account_id INT UNSIGNED NOT NULL,
    reference VARCHAR(100) NULL,
    created_by INT UNSIGNED NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_inv_contact (contact_id),
    INDEX idx_inv_status (status),
    INDEX idx_inv_due_date (due_date),
    INDEX idx_inv_doc_type (document_type),
    FOREIGN KEY (contact_id) REFERENCES contacts(id),
    FOREIGN KEY (journal_entry_id) REFERENCES journal_entries(id),
    FOREIGN KEY (ar_ap_account_id) REFERENCES accounts(id),
    FOREIGN KEY (created_by) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE invoice_lines (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    invoice_id INT UNSIGNED NOT NULL,
    description VARCHAR(500) NOT NULL,
    account_id INT UNSIGNED NOT NULL,
    quantity DECIMAL(10,4) NOT NULL DEFAULT 1.0000,
    unit_price DECIMAL(15,4) NOT NULL DEFAULT 0.0000,
    tax_amount DECIMAL(15,2) NOT NULL DEFAULT 0.00,
    line_total DECIMAL(15,2) NOT NULL DEFAULT 0.00,
    line_order SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_il_invoice (invoice_id),
    INDEX idx_il_account (account_id),
    FOREIGN KEY (invoice_id) REFERENCES invoices(id) ON DELETE CASCADE,
    FOREIGN KEY (account_id) REFERENCES accounts(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
